name: Python CI with SonarCloud
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonar:
    name: Run SonarCloud Analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.8"
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync --python ${{ matrix.python-version }}

      - name: Run tests with coverage
        run: |
          uv run python -W ignore::DeprecationWarning -m coverage run --rcfile=.coveragerc -m unittest discover
          uv run coverage report
          uv run coverage xml -o coverage.xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=ti-forest-sector-modelling
            -Dsonar.projectKey=TI-Forest-Sector-Modelling_TiMBA
            -Dsonar.projectName=TiMBA
            -Dsonar.projectVersion=1.3.0
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=test/**,**/test_*.py
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
